repo_name: 'iBot'
repo_info: >
  # iBot

  ## Here, we have Jarvis the toddler bot to provide instant support to users

  Author infos

  [![Binder](https://mybinder.org/badge.svg)](google.fr)
  [![Colab](https://colab.research.google.com/assets/colab-badge.svg)](google.fr)
  [![Nbviewer](https://raw.github.com/jupyter/design/master/logos/Badges/nbviewer_badge.svg?sanitize=true)](https://mybinder.org/badge.svg)](google.fr)
