name: iBot
channels:
- conda-forge
dependencies:
- python=3
- nb_conda_kernels
- pyyaml
- flake8
- pytest
- pytest-cov
# Some packages you're likly going to need
- pandas
- numpy
- scikit-learn
# Include pip based packages
- pip:
  - -e .
